# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.fulltextsearch:
      arguments:
        - "@router"
        - "@form.factory"
      class: AppBundle\Services\FulltextSearch
    app.hitlogger:
      arguments:
        - "@doctrine.orm.entity_manager"
      class: AppBundle\Services\HitLogger
    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
        -
          name: twig.extension