# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.fulltextsearch:
      arguments:
        - "@router"
        - "@form.factory"
      class: AppBundle\Services\FulltextSearch
    app.hitlogger:
      arguments:
        - "@doctrine.orm.entity_manager"
      class: AppBundle\Services\HitLogger
    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
        -
          name: twig.extension
    app.sitemap.nodes_subscriber:
      class:     AppBundle\EventListener\SitemapNodeSubscriber
      arguments:
        - "@router"
        - "@doctrine.orm.entity_manager"
      tags:
        - { name: "kernel.event_subscriber", priority: 100 }
    memcached:
        class: Memcached
        calls:
            - [ addServers, ["%memcache_hosts%"] ]
    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [ setMemcached, [ "@memcached" ] ]
    app.slugmanager:
        class: AppBundle\Services\SlugManager
        arguments:
          - "@doctrine.orm.entity_manager"
    app.htmlsanitization:
        class: AppBundle\Services\HtmlSanitization
    app.listener.forgot_password:
        class: AppBundle\EventListener\ForgotPasswordEventListener
        tags:
            - { name: kernel.event_listener, event: coop_tilleuls_forgot_password.create_token, method: onCreateToken }
    app.exception_controller:
        class: AppBundle\Controller\CustomExceptionController
        arguments:
            - '@twig'
            - '%kernel.debug%'
            - '@doctrine.orm.entity_manager'
            - '@router'