language: php
php:
    - 5.6
    - hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
env:
    - SYMFONY_VERSION=3.0.*
matrix:
    allow_failures:
        - php: hhvm
before_install:
    - composer self-update
    - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;
install: composer update --prefer-source --no-dev $COMPOSER_FLAGS
script: phpunit --coverage-text
before_script:
    - composer update --prefer-source --prefer-stable $COMPOSER_FLAGS