backend_new_node:
    path:     /new_node
    defaults: { _controller: "AppBundle:Backend:new_node" }
    methods:  [GET, POST]

backend_new_definition:
    path:     /{node_id}/new_definition
    defaults: { _controller: "AppBundle:Backend:new_definition" }
    methods:  [GET, POST]

backend_profile_view:
    path:     /profile/view
    defaults: { _controller: "AppBundle:Backend:profile_view" }

backend_profile_edit:
    path:     /profile/edit
    defaults: { _controller: "AppBundle:Backend:profile_edit" }
    methods:  [GET, POST]

backend_profile_changepassword:
    path:     /profile/change_password
    defaults: { _controller: "AppBundle:Backend:profile_changepassword" }
    methods:  [GET, POST]