definition_index:
    path:     /
    defaults: { _controller: "AppBundle:Definition:index" }
    methods:  GET

definition_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Definition:show" }
    methods:  GET

definition_new:
    path:     /new
    defaults: { _controller: "AppBundle:Definition:new" }
    methods:  [GET, POST]

definition_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Definition:edit" }
    methods:  [GET, POST]

definition_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Definition:delete" }
    methods:  DELETE
