page_manifesto:
    path:     /manifesto
    defaults: { _controller: "AppBundle:Page:manifesto" }

page_privacypolicy:
    path:     /privacy-and-cookies-policy
    defaults: { _controller: "AppBundle:Page:privacy_policy" }