app_definitions:
    resource: "@AppBundle/Resources/config/routing/definition.yml"
    prefix: /definition

app_hits:
    resource: "@AppBundle/Resources/config/routing/hit.yml"
    prefix: /hit

app_node:
    resource: "@AppBundle/Resources/config/routing/node.yml"
    prefix: /node

app_roles:
    resource: "@AppBundle/Resources/config/routing/role.yml"
    prefix: /role

app_users:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

app_page:
    resource: "@AppBundle/Resources/config/routing/page.yml"
    prefix: /page

app_dictionary:
    resource: "@AppBundle/Resources/config/routing/dictionary.yml"
    prefix: /dictionary

security_login:
    path: /security/login
    defaults: { _controller: "AppBundle:Security:login"}

default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods:  GET


