AppBundle\Entity\Role:
    type: entity
    table: bs_roles
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        isAdmin:
            type: boolean
            nullable: false
            column: is_admin
    lifecycleCallbacks: {  }
